apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-department
  template:
    metadata:
      labels:
        app: employee-department
    spec:
      containers:
        - name: employee-department
          image: 779846797240.dkr.ecr.us-east-1.amazonaws.com/employee-department-eks:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: employee-department-service
spec:
  type: LoadBalancer
  selector:
    app: employee-department
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
