apiVersion: v1
kind: Service
metadata:
  name: employee-department-service
spec:
  type: LoadBalancer
  selector:
    app: employee-department
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080